# Generated by Django 6.0.5 on 2026-05-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCita',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=40)),
                ('detalle', models.TextField(blank=True, default='')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'auditoría de cita',
                'verbose_name_plural': 'auditorías de citas',
                'db_table': 'auditoria_citas',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.BigAutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cancelada_por', models.CharField(blank=True, choices=[('paciente', 'Paciente'), ('medico', 'Médico'), ('admin', 'Admin')], max_length=10, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'cita',
                'verbose_name_plural': 'citas',
                'db_table': 'citas',
            },
        ),
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id_estado', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'estado de cita',
                'verbose_name_plural': 'estados de cita',
                'db_table': 'estados_cita',
            },
        ),
    ]
