# Generated by Django 6.0.5 on 2026-05-28 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('horarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriacita',
            name='actor_id_usuario',
            field=models.ForeignKey(db_column='actor_id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_horario',
            field=models.OneToOneField(db_column='id_horario', on_delete=django.db.models.deletion.CASCADE, to='horarios.horario'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_paciente',
            field=models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriacita',
            name='id_cita',
            field=models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, to='citas.cita'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_estado',
            field=models.ForeignKey(db_column='id_estado', default=1, on_delete=django.db.models.deletion.PROTECT, to='citas.estadocita'),
        ),
    ]
