# Generated by Django 6.0.5 on 2026-05-28 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horarios', '0001_initial'),
        ('medicos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='id_medico',
            field=models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.CASCADE, to='medicos.medico'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='check_hora_fin_gt_hora_inicio'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('id_medico', 'fecha', 'hora_inicio', 'hora_fin'), name='unique_medico_fecha_horario'),
        ),
    ]
