# Generated by Django 6.0.5 on 2026-05-28 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.BigAutoField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=200)),
                ('frecuencia', models.CharField(help_text='Ej: cada 8 horas', max_length=200)),
                ('duracion', models.CharField(blank=True, default='', max_length=100)),
                ('indicaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='citas.cita')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'recetas',
            },
        ),
    ]
