# Generated by Django 6.0.5 on 2026-05-28 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id_medico', models.OneToOneField(db_column='id_medico', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registro_profesional', models.CharField(blank=True, default='', max_length=60)),
                ('consultorio', models.CharField(blank=True, default='', max_length=60)),
                ('estado', models.CharField(default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'médico',
                'verbose_name_plural': 'médicos',
                'db_table': 'medicos',
            },
        ),
        migrations.CreateModel(
            name='MedicoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_especialidad', models.ForeignKey(db_column='id_especialidad', on_delete=django.db.models.deletion.CASCADE, to='medicos.especialidad')),
                ('id_medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.CASCADE, to='medicos.medico')),
            ],
            options={
                'verbose_name': 'médico-especialidad',
                'verbose_name_plural': 'médicos-especialidades',
                'db_table': 'medico_especialidad',
                'unique_together': {('id_medico', 'id_especialidad')},
            },
        ),
    ]
